#!/bin/sh

# git executable wrapper script for Git-Mediawiki to run tests without
# installing all the scripts and perl packages.

ROOT_DIR=$(dirname "$0")/..

GITPERLLIB="$ROOT_DIR${GITPERLLIB:+:$GITPERLLIB}"
PATH="$ROOT_DIR:$PATH"

export GITPERLLIB PATH

exec "${GIT_EXEC_PATH:-/usr/bin/}git" "$@"
