#!/bin/sh

# git executable wrapper script for Git-MediaWiki to run tests without
# installing all the scripts and perl packages.

ROOT_DIR=$(dirname "$0")/..

PERL5LIB="$ROOT_DIR${GITPERLLIB:+:$GITPERLLIB}"
PATH="$ROOT_DIR:$PATH"

export PERL5LIB PATH

exec "${GIT_EXEC_PATH:-/usr/bin/}git" "$@"
