---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - mediawiki_version: 1.35
            database_type: sqlite
            experimental: false
          - mediawiki_version: 1.36
            database_type: sqlite
            experimental: true
          - mediawiki_version: 1.37
            database_type: sqlite
            experimental: true

    env:
      PROJECT_NAME: Git-Mediawiki
      COMPOSER_VERSION: 2.1.14
      MW_INSTALL_PATH: /var/www/html
      MW_EXT_PATH: /var/www/html/extensions
      DB_ROOT_USER: root
      DB_ROOT_PWD: database
      MW_DB_TYPE: ${{ matrix.database_type }}
      MW_DB_SERVER: ${{ matrix.database_type }}
      MW_DB_PATH: /var/www/data
      MW_DB_USER: wiki
      MW_DB_PWD: wiki
      MW_DB_NAME: wiki
      DB_PRISTINE: /var/www/pristine
      SERVER_NAME: localhost

    container:
      image: mediawiki:${{ matrix.mediawiki_version }}
      ports:
        - 80:80

    services:
      some-mysql:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_ROOT_PWD }}

    steps:
      # https://getcomposer.org/download/
      - name: Get Composer and MediaWiki::API
        run: |
          apt update
          apt install -t stable -y unzip libmediawiki-api-perl \
              libdatetime-format-iso8601-perl
          php -r "copy('https://getcomposer.org/installer', 'installer');"
          php -r "copy('https://composer.github.io/installer.sig', 'expected');"
          echo `cat expected` " installer" | sha384sum -c -
          php installer --version=${{ env.COMPOSER_VERSION }}
          rm -f installer expected
          mv composer.phar /usr/local/bin/composer

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: ${{ env.PROJECT_NAME }}
          submodules: true

      - name: MediaWiki Composer Update
        run: |
          composer update --working-dir ${{ env.MW_INSTALL_PATH }}

      - name: MediaWiki Install
        run: >
          php ${{ env.MW_INSTALL_PATH }}/maintenance/install.php
          --pass=Password123456
          --server="http://${{ env.SERVER_NAME}}:80"
          --scriptpath=""
          --dbtype=${{ env.MW_DB_TYPE }}
          --dbserver=${{ env.MW_DB_SERVER }}
          --installdbuser=${{ env.DB_ROOT_USER }}
          --installdbpass=${{ env.DB_ROOT_PWD }}
          --dbname=${{ env.MW_DB_NAME }}
          --dbuser=${{ env.MW_DB_USER }}
          --dbpass=${{ env.MW_DB_PWD }}
          --dbpath=${{ env.MW_DB_PATH }}
          test WikiSysop

      - name: Pristine DB
        run: >
          mkdir -p ${{ env.DB_PRISTINE }} &&
          cp -r ${{ env.MW_DB_PATH }}/* ${{ env.DB_PRISTINE }}

      - name: Run Tests         # https://stackoverflow.com/a/50055449
        run: >
          timeout 80 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do
          sleep 1; done' ${{ env.SERVER_NAME }} 80 &&
          curl http://${{ env.SERVER_NAME}}:80/api.php &&
          make -C ${{ env.PROJECT_NAME }}/t test
