---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  PROJECT_NAME: Git-Mediawiki
  COMPOSER_VERSION: 2.1.14
  MW_INSTALL_PATH: /var/www/html
  MW_EXT_PATH: /var/www/html/extensions
  DB_ROOT_USER: root
  DB_ROOT_PWD: database
  MW_DB_PATH: /var/www/data
  MW_DB_USER: wiki
  MW_DB_PWD: wiki
  MW_DB_NAME: wiki
  DB_PRISTINE: /var/www/pristine.tgz
  SERVER_NAME: localhost

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - mediawiki_version: 1.35
            database_type: sqlite
            experimental: false
          - mediawiki_version: 1.36
            database_type: sqlite
            experimental: true
          - mediawiki_version: 1.37
            database_type: sqlite
            experimental: true

    env:
      MW_DB_TYPE: ${{ matrix.database_type }}
      MW_DB_SERVER: ${{ matrix.database_type }}

    container:
      image: mediawiki:${{ matrix.mediawiki_version }}
      ports:
        - 80:80

    steps:
      - name: MediaWiki Install
        run: >
          php ${{ env.MW_INSTALL_PATH }}/maintenance/install.php
          --pass=Password123456
          --server="http://${{ env.SERVER_NAME}}"
          --scriptpath=""
          --dbtype=${{ env.MW_DB_TYPE }}
          --dbserver=${{ env.MW_DB_SERVER }}
          --installdbuser=${{ env.DB_ROOT_USER }}
          --installdbpass=${{ env.DB_ROOT_PWD }}
          --dbname=${{ env.MW_DB_NAME }}
          --dbuser=${{ env.MW_DB_USER }}
          --dbpass=${{ env.MW_DB_PWD }}
          --dbpath=${{ env.MW_DB_PATH }}
          test WikiSysop

      - name: Stage artifacts
        run: |
          mkdir -p ${{ matrix.mediawiki_version }}
          tar -C ${{ env.MW_DB_PATH }} -cvf ${{ matrix.mediawiki_version }}/db.tar .
          cp ${{ env.MW_INSTALL_PATH }}/LocalSettings.php ${{ matrix.mediawiki_version }}/

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: runtime-${{ matrix.mediawiki_version }}
          path: ${{ matrix.mediawiki_version }}

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - mediawiki_version: 1.35
            database_type: sqlite
            experimental: false
          - mediawiki_version: 1.36
            database_type: sqlite
            experimental: true
          - mediawiki_version: 1.37
            database_type: sqlite
            experimental: true

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: ${{ env.PROJECT_NAME }}
          submodules: true

      - name: Load artifacts
        uses: actions/download-artifact@v3
        with:
          name: runtime-${{ matrix.mediawiki_version }}
          path: ${{ matrix.mediawiki_version }}

      - name: Deploy artifacts
        run: |
          sudo mkdir ${{ env.MW_DB_PATH }}
          sudo chmod 1777 ${{ env.MW_DB_PATH }}
          sudo tar -C ${{ env.MW_DB_PATH }} -xvf ${{ matrix.mediawiki_version }}/db.tar
          sudo cp ${{ matrix.mediawiki_version }}/LocalSettings.php ${{ env.MW_INSTALL_PATH }}/
          ls -l ${{ env.MW_DB_PATH }} ${{ env.MW_INSTALL_PATH }}/LocalSettings.php
